### ISSUE TITLE
Crosswalk values for ILCS reference are too specific in some cases

### ISSUE THREAD

**Issue by bepetersn** [sc3/python-iucr#5]
In an effort to handle #3, I believe a bug has been introduced. Adding subsection arguments into the `lookup_by_ilcs` method signature (which @ghing did initially) has caused a problem, in that it appears to have broken the functionality of looking up an IUCR code given an ILCS reference, for statutes which are specified past the section level. 

For now I am ignoring this, but an example would be the following ILCS statute in the [crosswalk document](https://github.com/sc3/python-iucr/blob/master/iucr/data/ilcs2iucr.csv#L221):

> 720-550/4(a)

**Comment by bepetersn** [comment]
Maybe this isn't an issue. I'm going to try to get #3 done.

**Comment by ghing** [comment]
Yeah, wouldn't the call for that just be:

```
iucr.lookup_by_ilcs("720", "550", "4", "a")
```

If you're talking about breaking

```
iucr.lookup_by_ilcs("720-550/4(a)")
```

I'm ok with getting rid of support for passing the full reference string.

Also, remember that we could break out the subsections in our CSV if needed.

**Comment by bepetersn** [comment]
No, the error was a weird one that was happening with the first call, using the bits. But that's because the tests weren't actually erroring the way I wanted them to yet. Specifically, we weren't using the subsection at all in the lookup, although it was passed in as a different variable. Thus, the cases where the ILCS goes down past sections didn't work. When you passed in `iucr.lookup_by_ilcs("720", "550", "4", "a")`, you got: 

> KeyError: 720-550/4

But now I wrote a clause to use the subsection bits, and all the test cases fail equally.

**Comment by bepetersn** [comment]
Above, were you suggesting 1) breaking the csv data down into bits, 2) dropping the subsections, or something else entirely?
